version: 2
services:
  TopoANode1:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/reconfiguration:latest
    container_name: TopoANode1
    hostname: TopoANode1
    tty: true
    volumes:
    - /root/NFS500/networktopo/TopoANode1/config:/tendermint/config
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=3b51d6dd8cc73b942a4deb17f0743307815acb30@TopoANode3:26656,4800332b8df1078c2272d39f1ebbd9ac2ecbd60c@TopoANode2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - TopoAnode1
  TopoANode2:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/reconfiguration:latest
    container_name: TopoANode2
    hostname: TopoANode2
    tty: true
    volumes:
    - /root/NFS500/networktopo/TopoANode2/config:/tendermint/config
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=16196464fb22676979bfc7b517d14cb8f6e3b604@TopoANode1:26656,8ba12d61ca38e21ffae72711ac1ae2c0e965714a@TopoANode4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - TopoAnode2
  TopoANode3:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/reconfiguration:latest
    container_name: TopoANode3
    hostname: TopoANode3
    tty: true
    volumes:
    - /root/NFS500/networktopo/TopoANode3/config:/tendermint/config
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=16196464fb22676979bfc7b517d14cb8f6e3b604@TopoANode1:26656,8ba12d61ca38e21ffae72711ac1ae2c0e965714a@TopoANode4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - TopoAnode3
  TopoANode4:
    image: registry-vpc.cn-beijing.aliyuncs.com/ruc500/reconfiguration:latest
    container_name: TopoANode4
    hostname: TopoANode4
    tty: true
    volumes:
    - /root/NFS500/networktopo/TopoANode4/config:/tendermint/config
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - tendermint node --p2p.persistent_peers=3b51d6dd8cc73b942a4deb17f0743307815acb30@TopoANode3:26656,4800332b8df1078c2272d39f1ebbd9ac2ecbd60c@TopoANode2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore
    networks:
      tendermintnet1:
        aliases:
        - TopoAnode4
